### ISSUE TITLE
home切出去之后，再次进入如何显示悬浮窗？

### ISSUE THREAD

**Issue by woomartin** [JieYuShi/FloatWindowProject#2]
前提是不知道从哪个页面进入退出。

**Comment by rchaocai** [comment]
抱歉才看到，记得我们当时是通过监听home键的广播来实现隐藏的，展示的话我们的应用是必须经过主activity的，所以就在主activity进行展示

mark_mww <notifications@github.com> 于2018年7月19日周四 下午2:38写道：
